import { GCNumber } from '../textFields/constants'

export const fields = [
  {
    name: 'propertyName',
    label: 'Property Name',
    required: true,
    disable: true,
    type: 'string',
    placeHolderText: 'Taj Lands End',
  },
  {
    name: 'bookingNumber',
    label: 'Itinerary  Number',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : 21305B0075626',
  },
  {
    name: 'invoiceamount',
    label: 'Invoice Amount',
    required: true,
    type: 'number',
    disable: false,
    placeHolderText: 'ex : 2100.00',
  },
  {
    name: 'checkIn',
    label: 'Check-In Date',
    required: true,
    type: 'date',
    disable: false,
  },
  {
    name: 'checkOut',
    label: 'Check-Out Date',
    required: true,
    type: 'date',
    disable: false,
  },
  {
    name: 'invoiceNumber',
    label: 'Invoice Number',
    type: 'string',
    required: true,
    disable: false,
    placeHolderText: 'ex : WEB_23105',
  },

  {
    name: 'redeemNeucoins',
    label: 'Enter Amount to Redeem',
    required: true,
    type: 'number',
    placeHolderText: 'ex : 1000',
  },
]

export const neuCoinsReInstateFields = [
  {
    name: 'propertyName',
    label: 'Property Name',
    required: true,
    disable: true,
    type: 'string',
    placeHolderText: 'Taj Lands End',
  },
  {
    name: 'bookingNumber',
    label: 'Itinerary  Number',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : 21305B0075626',
  },
  {
    name: 'invoiceamount',
    label: 'Invoice Amount',
    required: true,
    type: 'number',
    disable: false,
    placeHolderText: 'ex : 2100.00',
  },
  {
    name: 'checkIn',
    label: 'Check-In Date',
    required: true,
    type: 'date',
    disable: false,
  },
  {
    name: 'checkOut',
    label: 'Check-Out Date',
    required: true,
    type: 'date',
    disable: false,
  },
  {
    name: 'invoiceNumber',
    label: 'Invoice Number',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : WEB_23105',
  },
  {
    name: 'phone',
    label: 'Mobile Number',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : +919966xxxx00',
  },

  {
    name: 'reinstateNeucoins',
    label: 'Enter Neucoins Amount to Reverse',
    required: true,
    type: 'number',
    placeHolderText: 'ex : 1000',
  },
  {
    name: 'reasonforreversal',
    label: 'Select Reson for reversal',
    required: true,
    type: 'dropdown',
    placeHolderText: 'ex : Guest didn`t appear at hotel',
    options: ['Order Cancellation', 'Change in Plans'],
  },
]

export const gcReinstateInstateFields = [
  {
    name: 'propertyName',
    label: 'Property Name',
    required: true,
    disable: true,
    type: 'string',
    placeHolderText: 'Taj Lands End',
  },
  {
    name: GCNumber,
    label: 'GiftCard Number*',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : XXXX XXXX XXXX XXXX',
  },
  {
    name: 'bookingNumber',
    label: 'Itinerary  Number',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : 21305B0075626',
  },
  {
    name: 'invoiceamount',
    label: 'Invoice Amount',
    required: true,
    type: 'number',
    disable: false,
    placeHolderText: 'ex : 2100.00',
  },
  {
    name: 'checkIn',
    label: 'Check-In Date*',
    required: true,
    type: 'date',
    disable: false,
  },
  {
    name: 'checkOut',
    label: 'Check-Out Date*',
    required: true,
    type: 'date',
    disable: false,
  },
  {
    name: 'invoiceNumber',
    label: 'Invoice Number*',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : WEB_23105',
  },
  {
    name: 'phone',
    label: 'Mobile Number*',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : +919966xxxx00',
  },

  {
    name: 'reinstateGiftCard',
    label: 'Amount to Reverse*',
    required: true,
    type: 'number',
    placeHolderText: 'ex : 1000',
  },
  {
    name: 'originalApprovalCode',
    label: 'Original ApprovalCode*',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : 115152243',
  },
  {
    name: 'originalBatchNumber',
    label: 'Original BatchNumber*',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : 14413770',
  },
  {
    name: 'originalTransactionId',
    label: 'Original TransactionId*',
    required: true,
    type: 'string',
    placeHolderText: 'ex : 98',
  },
  {
    name: 'originalAmount',
    label: 'Original Amount*',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : 100',
  },
  {
    name: 'reasonforreversal',
    label: 'Select Reason for reversal*',
    required: true,
    type: 'dropdown',
    placeHolderText: 'ex : Guest didn`t appear at hotel',
    options: [
      // 'Order Cancellation',
      // 'Change in Plans',
      'Payment Failure',
      'Cancelled Booking',
      'Manual Adjustment',
    ],
  },
]

export const voucherReinstateFields = [
  {
    name: 'propertyName',
    label: 'Property Name',
    required: true,
    disable: true,
    type: 'string',
    placeHolderText: 'Taj Lands End',
  },
  {
    name: 'memberID',
    label: 'Member ID*',
    required: true,
    disable: true,
    type: 'string',
    placeHolderText: 'ex : 5173',
  },

  {
    name: 'bitDate',
    label: 'Created On*',
    required: true,
    disable: true,
    type: 'string',
    placeHolderText: 'ex : XXX-XX-XXT00:00:00+05:30',
  },
  {
    name: 'bitId',
    label: 'Bit ID*',
    required: true,
    disable: true,
    type: 'string',
    placeHolderText: 'ex : 219I1H7BAD08A28PXXXXXXXC4',
  },

  {
    name: 'memberType',
    label: 'Member Type*',
    required: true,
    disable: true,
    type: 'string',
    placeHolderText: 'ex : Epicure',
  },
  {
    name: 'reasonforreversal',
    label: 'Select Reason for reversal*',
    required: true,
    type: 'dropdown',
    placeHolderText: 'ex : Guest didn`t appear at hotel',
    options: [
      // 'Order Cancellation',
      // 'Change in Plans',
      'Payment Failure',
      'Cancelled Booking',
      'Manual Adjustment',
    ],
  },
]

export const ccAvenueGeneratePayments = [
  {
    name: 'guestName',
    label: 'Guest Name',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex: XXX XXX',
  },
  {
    name: 'phone',
    label: 'Mobile Number*',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : +919966xxxx00',
  },
  {
    name: 'email',
    label: 'Guest Email*',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : sxxxxxxx@gmail.com',
  },
  {
    name: 'orderId',
    label: 'Order ID',
    required: true,
    type: 'string',
    disable: false,
    placeHolderText: 'ex : WEB_9981',
  },
  {
    name: 'orderamount',
    label: 'Order Amount',
    required: true,
    type: 'number',
    disable: false,
    placeHolderText: 'ex : 2100.00',
  },
]

export const gcVoucherRedemption = [
  {
    name: 'propertyName',
    label: 'Property Name',
    required: true,
    disable: true,
    type: 'string',
    placeHolderText: 'Taj Lands End',
  },
  {
    name: 'newExpiryDate',
    label: 'New Expiry Date',
    required: true,
    type: 'date',
    disable: false,
  },
  {
    name: 'memberID',
    label: 'Member ID*',
    required: true,
    disable: true,
    type: 'string',
    placeHolderText: 'ex : 5173',
  },

  {
    name: 'bitDate',
    label: 'Created On*',
    required: true,
    disable: true,
    type: 'string',
    placeHolderText: 'ex : XXX-XX-XXT00:00:00+05:30',
  },
  {
    name: 'phone',
    label: 'Mobile Number*',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : +919966xxxx00',
  },
  {
    name: 'email',
    label: 'Guest Email*',
    required: true,
    disable: false,
    type: 'string',
    placeHolderText: 'ex : sxxxxxxx@gmail.com',
  },
  {
    name: 'reasonforExtension',
    label: 'Select Reson for Extension',
    required: true,
    type: 'dropdown',
    placeHolderText: 'ex : Extended stay due to travel disruption',
    options: ['Order Issue', 'Change in Plans '],
  },
]
